### ISSUE TITLE
In 3.1.0, calls to JWT.Decode<T> throw System.InvalidCastException

### ISSUE THREAD

**Issue by jonsagara** [dvsekhvalnov/jose-jwt#156]
Hi,

After upgrading from 3.0.0 to 3.1.0, my calls to JWT.Decode<T> started throwing `System.InvalidCastException`:

```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'JoseJwtDecodeException.SamplePayloadModel'.
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonConverter[] converters)
   at Jose.NewtonsoftMapper.Parse[T](String json)
   at Jose.JWT.Decode[T](String token, Object key, JwsAlgorithm alg, JwtSettings settings)
   at JoseJwtDecodeException.Program.Main(String[] args) in C:\Dev\SANDBOX\JoseJwtDecodeException\src\JoseJwtDecodeException\Program.cs:line 30
```

If I switch back to 3.0.0, everything works perfectly as it did before.

I have created a repo with reproduction steps here: https://github.com/jonsagara/JoseJwtDecodeException

But for posterity in this issue, here is the code under test:

```csharp
class Program
{
    static void Main(string[] args)
    {
        var secret = "xB7EFoU1ExrPRkurvoVNN1L1MXI1nwtvtP54p1pNLdI=";
        var secretBytes = WebEncoders.Base64UrlDecode(secret);
        var payload = new SamplePayloadModel
        {
            jti = Guid.Parse("7eb8f0e3-1144-4ed2-b4d9-be266f68f212").ToString(),
            iss = "My Application",
            iat = 1617749964L, // Approximately 2021-04-06 15:59 Pacific Daylight Time
            aud = "https://example.com",
            sub = "testperson@example.com",
        };

        // Encode the payload.
        var jwt = JWT.Encode(payload, secretBytes, JwsAlgorithm.HS256);
        Console.WriteLine($"jwt: {jwt}");

        // Decode the payload, and serialize it as JSON for display.
        try
        {
            var decodedPayload = JWT.Decode<SamplePayloadModel>(jwt, secretBytes, JwsAlgorithm.HS256);
            var decodedPayloadJson = JsonConvert.SerializeObject(decodedPayload, Formatting.Indented);
            Console.WriteLine("decoded jwt payload:");
            Console.WriteLine(decodedPayloadJson);
        }
        catch (Exception ex)
        {
            Console.Error.WriteLine("*** Failed to decode JWT ***");
            Console.Error.WriteLine(ex);
        }
    }
}

public class SamplePayloadModel
{
    /// <summary>
    /// JWT ID
    /// </summary>
    public string jti { get; set; }

    /// <summary>
    /// Issuer.
    /// </summary>
    public string iss { get; set; }

    /// <summary>
    /// Issued At. When the JWT was issued.
    /// </summary>
    public long iat { get; set; }

    /// <summary>
    /// Audience. Must match the request authority (e.g., https://example.com).
    /// </summary>
    public string aud { get; set; }

    /// <summary>
    /// Subject.
    /// </summary>
    public string sub { get; set; }
}
```

**Comment by dvsekhvalnov** [comment]
Hi @jonsagara , thanks i'll take a look.  There were some changes in Newtonsoft configuration, most likely related.

I feel i need to get rid of newtonsoft altogether.

**Comment by dvsekhvalnov** [comment]
@jonsagara fix here: https://github.com/dvsekhvalnov/jose-jwt/commit/f00912e847a148fab78360b8ca6e5fe8be822644

will try to publish to nuget todayish.

**Comment by jonsagara** [comment]
Thank you for the quick turnaround!

**Comment by dvsekhvalnov** [comment]
@jonsagara   , please find it on nuget https://www.nuget.org/packages/jose-jwt/3.1.1
(or https://github.com/dvsekhvalnov/jose-jwt/releases/tag/v3.1.1)

Would appreciate if you can try it and come back with feedback so we can close issue.

Also i'd probably try to get rid of newtonsoft in v3.2 in favor of System.Text.Json (aka #130) for netcore 3+. May be something to watch out for.

**Comment by jonsagara** [comment]
All my tests are green again. Thank you!
