### ISSUE TITLE
'Windows Cryptography Next Generation (CNG) is not supported on this platform.'

### ISSUE THREAD

**Issue by priyankamauryaa** [dvsekhvalnov/jose-jwt#194]
Hi, I'm getting below error while trying to decrypt jwe using- JWE.Decrypt(encryptedIdToken.id_token, jwk).Plaintext

[10:39:11 INF] ex Message: 'Windows Cryptography Next Generation (CNG) is not supported on this platform.'

[10:39:11 INF] ex InnerException: ''

login Failed: 'System.PlatformNotSupportedException: Windows Cryptography Next Generation (CNG) is not supported on this platform.

   at System.Security.Cryptography.CngKeyBlobFormat.get_EccPrivateBlob()

   at Jose.keys.EccKey.New(Byte[] x, Byte[] y, Byte[] d, CngKeyUsages usage)

   at Jose.Jwk.CngKey(CngKeyUsages usage)

   at Jose.EcdhKeyManagement.Unwrap(Byte[] encryptedCek, Object key, Int32 cekSizeBits, IDictionary`2 header)

   at Jose.EcdhKeyManagementWithAesKeyWrap.Unwrap(Byte[] encryptedCek, Object key, Int32 cekSizeBits, IDictionary`2 header)

   at Jose.JWE.Decrypt(String jwe, Object key, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings)
   
   This code seems working fine in windows but on linux I'm getting the error.

**Comment by dvsekhvalnov** [comment]
HI @priyankamauryaa , 

well it means what it says - no support besides Windows platform. Unfortunetly Ecdh key management do not have managed version in .net runtime, so library relies on native CNG libraries, those available only in windows.

**Comment by dvsekhvalnov** [comment]
No, unfortunately no way at the moment. I'd happy to add managed solution once .net support it.

**Comment by priyankamauryaa** [comment]
.net is not supporting it yet ? Can you please help me to know if .net supports to use EC key to decrypt ECDH-ES+A128KW encrypted token on linux?

**Comment by dvsekhvalnov** [comment]
.netcore not supporting ECDH on Linux. 

You can decode token on Windows platform.

**Comment by priyankamauryaa** [comment]
Thank you for your response.
