### ISSUE TITLE
Illegal base64url string! Parameter name: input

### ISSUE THREAD

**Issue by RushabhJbspl** [dvsekhvalnov/jose-jwt#213]
Hello,
I am facing "Illegal base64url string! Parameter name: input" error while decoding the token : 
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Illegal base64url string!
Parameter name: input
  Source=jose-jwt
  StackTrace:
   at Jose.Base64Url.Decode(String input)
   at Jose.JWT.DecodeBytes(String token, Object key, Nullable`1 expectedJwsAlg, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings, Byte[] payload)
   at Jose.JWT.Decode(String token, Object key, JwsAlgorithm alg, JwtSettings settings, String payload)

App Code:
byte[] secretKey = Encoding.ASCII.GetBytes(Key);                    
string Response = IsEncrypt ? JWT.Encode(Message, secretKey, JwsAlgorithm.HS256) : JWT.Decode(Message, secretKey, JwsAlgorithm.HS256);

**Comment by dvsekhvalnov** [comment]
Hi @RushabhJbspl , 

mind posting token?
