### ISSUE TITLE
Question: Decode token encrypted by Nimbus JOSE

### ISSUE THREAD

**Issue by thangtx** [dvsekhvalnov/jose-jwt#70]
I need decode token from Java code using Nimbus
```java
public final static String createPKIJwe(String payloadData, String randomIdentifier, RSAPublicKey publicKey)
			throws Exception {
		long currentTime = new Date().getTime() / 1000;

		JWEHeader updatedHeader = new JWEHeader.Builder(JWEAlgorithm.RSA1_5, EncryptionMethod.A128GCM).keyID(randomIdentifier)
				.type(JOSEObjectType.JOSE).customParam("iat", currentTime).build();

		Payload payload = new Payload(payloadData);

		JWEObject jweObject = new JWEObject(updatedHeader, payload);
		RSAEncrypter encrypter = new RSAEncrypter(publicKey);
		jweObject.encrypt(encrypter);

		return jweObject.serialize();

	}

	public final static String createPKIJws(String encryptedJwe) throws Exception {

		RSAPrivateKey privateKey = (RSAPrivateKey) getPrivateKey();
		// Create RSA-signer with the private key
		JWSSigner signer = new RSASSASigner(privateKey);

		// Prepare JWS object with simple string as payload
		JWSObject jwsObject = new JWSObject(new JWSHeader.Builder(JWSAlgorithm.RS256).type(JOSEObjectType.JOSE).build(),
				new Payload(encryptedJwe));

		// Compute the RSA signature
		jwsObject.sign(signer);
		String signedJws = jwsObject.serialize();

		return signedJws;
	}
```
But when I decrypt with jose-jwt:
```csharp
var token = JWT.Decode(requestData, rsa,JweAlgorithm.RSA1_5,JweEncryption.A128GCM);
```
It throw exception:
```csharp
Jose.IntegrityException : Invalid signature.
   at Jose.JWT.DecodeBytes(String token, Object key, Nullable`1 expectedJwsAlg, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings)
   at Jose.JWT.Decode(String token, Object key, Nullable`1 jwsAlg, Nullable`1 jweAlg, Nullable`1 jweEnc, JwtSettings settings)
   at Jose.JWT.Decode(String token, Object key, JweAlgorithm alg, JweEncryption enc, JwtSettings settings)
```
Please help me how to decode this by jose-jwt.
Thank you.

**Comment by dvsekhvalnov** [comment]
Hi @thangtx ,

1. first thing to verify is that you using same key pair. If you do encryption with RSA public key, make sure you passing corresponding private key to `JWT.Decode`.  

Same for signing, if you sign with private key -> verify with public.

2. second, are you encrypting and then signing encrypted token again? What the rational behind that?

P.S> you don't need to pass alg to Decode method, just `var token = JWT.Decode(requestData, key`) will work.

**Comment by thangtx** [comment]
Hi @dvsekhvalnov 
Thank you for quick reply, I have decrypt encrypted data.
