### ISSUE TITLE
AES GCM exception on .NET Core

### ISSUE THREAD

**Issue by sidshetye** [dvsekhvalnov/jose-jwt#78]
If using `token = Jose.JWT.Encode(payload, secretKey, JweAlgorithm.DIR, JweEncryption.A256GCM);` inside a .NET Core 2.0 app, you get an exception as follows on Ubuntu 16.04.

```
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'bcrypt.dll': The specified module or one of its dependencies could not be found.
 (Exception from HRESULT: 0x8007007E)
   at Jose.native.BCrypt.BCryptOpenAlgorithmProvider(IntPtr& phAlgorithm, String pszAlgId, String pszImplementation, UInt32 dwFlags)
   at Jose.AesGcm.OpenAlgorithmProvider(String alg, String provider, String chainingMode)
   at Jose.AesGcm.Encrypt(Byte[] key, Byte[] iv, Byte[] aad, Byte[] plainText)
   at Jose.AesGcmEncryption.Encrypt(Byte[] aad, Byte[] plainText, Byte[] cek)
   at Jose.JWT.EncodeBytes(Byte[] payload, Object key, JweAlgorithm alg, JweEncryption enc, Nullable`1 compression, IDictionary`2 extraHeaders, JwtSettings settings)
   at json_jwt_playground.Program.Main(String[] args) in /home/testuser/testproj/json-jwt-playground/Program.cs:line 58
```

Realize this is due to AES-GCM -> bcrypt.dll (which is a Windows layer) - do you plan on having AES GCM working on .NET Core Linux?

**Comment by dvsekhvalnov** [comment]
Hi @sidshetye ,

there is no cross-platform way to do aes-gcm in .net. See https://github.com/dotnet/corefx/issues/7023
