### ISSUE TITLE
bcrypt.dll not found issue when using JWE encryption in .Net Core PCF

### ISSUE THREAD

**Issue by KiranKumar7834** [dvsekhvalnov/jose-jwt#91]
Hi Team,
I am getting below exception while testing JWE Encoding service written in .Net Core. and deployed in PCF.

2018-04-25T21:05:48.894+05:30 [APP/PROC/WEB/0] [OUT] System.DllNotFoundException: Unable to load DLL 'bcrypt.dll': The specified module or one of its dependencies could not be found.

Manifest file detaiils:

applications:
- name: xxx.xxx.xxx.xxxxx
  buildpack: dicf_dotnet_core_buildpack_latest
  stack: cflinuxfs2
  command: dotnet xxx.xxx.xxx.xxxxx
  instances: 1
  memory: 128M
  disk_quota: 1GB
  health-check-type: none
  timeout: 80

Stack Trace:

2018-04-26T14:30:08.428+05:30 [APP/PROC/WEB/0] [OUT] ++++++++++++ Key GenerationStarted++++++++++++++++
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] System.DllNotFoundException: Unable to load DLL 'bcrypt.dll': The specified module or one of its dependencies could not be found.
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] (Exception from HRESULT: 0x8007007E)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.native.BCrypt.BCryptOpenAlgorithmProvider(IntPtr& phAlgorithm, String pszAlgId, String pszImplementation, UInt32 dwFlags)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.AesGcm.OpenAlgorithmProvider(String alg, String provider, String chainingMode)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.AesGcm.Decrypt(Byte[] key, Byte[] iv, Byte[] aad, Byte[] cipherText, Byte[] authTag)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.AesGcmEncryption.Decrypt(Byte[] aad, Byte[] cek, Byte[] iv, Byte[] cipherText, Byte[] authTag)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.JWT.DecryptBytes(Byte[][] parts, Object key, Nullable`1 jweAlg, Nullable`1 jweEnc, JwtSettings settings)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.JWT.DecodeBytes(String token, Object key, Nullable`1 expectedJwsAlg, Nullable`1 expectedJweAlg, Nullable`1 expectedJweEnc, JwtSettings settings)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at Jose.JWT.Decode(String token, Object key, JwtSettings settings)
2018-04-26T14:30:08.626+05:30 [APP/PROC/WEB/0] [OUT] at DFS.Consumer.API.Enroll.Handler.EnrollHandler.DecryptSensitiveData(String decryptedData) in C:\DFS_Recharge\DFS.Consumer.API.Enroll\DFS.Consumer.API.Enroll\Handler\EnrollHandler.cs:line 51
2018-04-26T14:30:08.630+05:30 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: DFS.Consumer.API.Enroll.Controllers.EnrollController[0]
2018-04-26T14:30:08.630+05:30 [APP/PROC/WEB/0] [OUT] ++++++++++++++++++++++++++ MiCrosoft Enroll request failed Unexpected character encountered while parsing value: e. Path '', line 0, position 0. ++++++++++++++++++++++++++
2018-04-26T14:30:08.632+05:30 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
2018-04-26T14:30:08.632+05:30 [APP/PROC/WEB/0] [OUT] Executed action method DFS.Consumer.API.Enroll.Controllers.EnrollController.Enroll (DFS.Consumer.API.Enroll), returned result Microsoft.AspNetCore.Mvc.ObjectResult.
2018-04-26T14:30:08.700+05:30 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[4]
2018-04-26T14:30:08.700+05:30 [APP/PROC/WEB/0] [OUT] No information found on request to perform content negotiation.
2018-04-26T14:30:08.705+05:30 [APP/PROC/WEB/0] [OUT] [40m[37mdbug[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[2]
2018-04-26T14:30:08.705+05:30 [APP/PROC/WEB/0] [OUT] Selected output formatter 'Microsoft.AspNetCore.Mvc.Formatters.HttpNoContentOutputFormatter' and content type 'application/json' to write the response.
2018-04-26T14:30:08.706+05:30 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor[1]
2018-04-26T14:30:08.706+05:30 [APP/PROC/WEB/0] [OUT] Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
2018-04-26T14:30:08.736+05:30 [APP/PROC/WEB/0] [OUT] [40m[32minfo[39m[22m[49m: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
2018-04-26T14:30:08.736+05:30 [APP/PROC/WEB/0] [OUT] Executed action DFS.Consumer.API.Enroll.Controllers.EnrollController.Enroll (DFS.Consumer.API.Enroll) in 747.0905ms

Algorithm used: RSA-AOEP algorithm and A256GCM encryption.

Sample Code:

 public string DecryptSensitiveData(string decryptedData)
        {

            _logger.LogDebug("++++++++++++ Key GenerationStarted++++++++++++++++");
            try
            {
                var privateKey = new X509Certificate2(@"./Certificates/xxxxxxxx.pfx", _settings.password).GetRSAPrivateKey();
                decryptedData = Jose.JWT.Decode(decryptedData, privateKey);

            }
            catch (Exception ex)
            {

                Console.WriteLine(ex);
            }

            return decryptedData;
        }

**Comment by dvsekhvalnov** [comment]
Hi @KiranKumar7834 ,

well exception clearly saying no `bcrypt.dll` .   I'm assuming you running on some version of linux?

**Comment by KiranKumar7834** [comment]
Hi dvsekhvalnov,
Yes i am... this is the stack: cflinuxfs2.

Thanks,
Kiran

**Comment by dvsekhvalnov** [comment]
@KiranKumar7834 ,

well, this is state of .netcore crypto support on linux unfortunately. AES-GCM is not supported and i'm not aware if there are any default library on linux (like `brcypt.dll` for windows) which can provide interoperability across all *nix distros for .netcore.

See: https://github.com/dotnet/corefx/issues/7023  After 2 years support is still in the air.

I'd recommend to switch to different encryption if you want to run it on linux, possible AES-CBC-HMAC.

**Comment by billgatesfan** [comment]
I tried the same as KiranKumar7834, and also got the same error message. But in my case, I am trying now with .Net Core SDK 3.0.100-preview7-012821, which is now supposed to support AES-GCM (https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0#cryptography-ciphers).   

I am using the PCF .Net Core buildpack v2.2.13, with dotnet-runtime.3.0.0-preview7.linux-amd64-38421a8a.tar.xz.

@dvsekhvalnov : As I don't control the cipher alg (cipher is chosen by a big SW manufacturer, providing CF services) and am still a crypto newbie, may I ask you your opinion if this issue could potentionally be fixed with recent .Net Core 3.x changes?

This could maybe also help this guy : https://github.com/dvsekhvalnov/jose-jwt/issues/78 ;-).

**Comment by dvsekhvalnov** [comment]
Hi @billgatesfan , yeah if it really works on *nix, managed AES-GCM implementation should fix the issue. I'm still waiting for GA release to add newer implementations for .net core 3.

**Comment by ardove** [comment]
Any updates on this rather old issue? 3 has been released (in addition to 5 and 6).

**Comment by dvsekhvalnov** [comment]
Hi @ardove , 

if we talking about AES GCM encryption, jose-jwt v3+ using managed encryption with NETSTANDARD2_1: https://github.com/dvsekhvalnov/jose-jwt/blob/master/jose-jwt/crypto/AesGcmNetCore.cs

It should work without bcrypt.dll. Assuming .net implements it on underlying OS.

**Comment by ardove** [comment]
Yeah, ok, cool, I just realized we're a couple versions behind, so I'll re-test. Thank you!

**Comment by dvsekhvalnov** [comment]
Cool, let me know if all works and i'll close it :)

**Comment by ardove** [comment]
@dvsekhvalnov, yeah, it looks like it's working as I'd expect. thanks a bunch!

**Comment by dvsekhvalnov** [comment]
Awesome, let me close it !
